trigger: none

pr:
  branches:
    include:
      - main

pool: 'My-AP-DevTF'

variables:
  Work_Dir: '$(System.DefaultWorkingDirectory)/Charlie_PROD_Root'
  Service_Connection: 'MyADO_Azure_SC2'

stages:
- stage: TerraformInit
  displayName: 'Terraform Init'
  jobs:
  - job: TerraformInit
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

- stage: TerraformValidate
  displayName: 'Terraform Validate'
  dependsOn: TerraformInit
  jobs:
  - job: TerraformValidate
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(Work_Dir)'

- stage: TerraformPlan
  displayName: 'Terraform Plan'
  dependsOn: TerraformValidate
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Work_Dir)'
        environmentServiceNameAzureRM: $(Service_Connection)
