trigger : none

pool: 'My-AP-DevTF'

variables:
  Work_Dir : '$(System.DefaultWorkingDirectory)/Charlie_PROD_Root'
  Service_Connection : 'MyADO_Azure_SC2'

stages:

- stage: TerraformInit
  displayName: 'Terraform Init'
  jobs:
  - job: TerraformInit
    displayName: 'Terraform Init Job'
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

- stage: TerraformPlan
  displayName: 'Terraform Plan'
  dependsOn: TerraformInit
  jobs:
  - job: TerraformInitandPlan
    displayName: 'Terraform Init and Plan Job'
    steps: 
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Work_Dir)'
        environmentServiceNameAzureRM: $(Service_Connection)

- stage: ManualValidation
  displayName: 'Manual Validation'
  dependsOn: TerraformPlan
  pool: server
  jobs:
  - job: ManualValidation
    displayName: 'Manual Validation Job'
    steps:
    - task: ManualValidation@1
      displayName: 'Manual Validation Step'
      inputs:
        notifyUsers: 'sahil.sr123@outlook.com'
        instructions: 'Please validate the Terraform plan before proceeding to apply changes.'          

- stage: TerraformApply
  displayName: 'Terraform Apply'
  dependsOn: ManualValidation
  jobs:
  - job: TerraformInitandApply
    displayName: 'Terraform Init and Apply Job'
    steps:
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: $(Service_Connection)
        backendAzureRmStorageAccountName: 'stappcicd0002'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Work_Dir)'
        environmentServiceNameAzureRM: $(Service_Connection)
            